#!/usr/bin/perl -I/var/www/macrophile.com/lib

# Delete a user
# (c) 2001-2013, Phillip Pollard, <bennie@macrophile.com>

my $table = 'users';

# Pragma

use Macro;
use Term::Query qw(query);
use strict;

# Main

my $macro = new Macro;

my $username = query('Username to DELETE: ','d','BigFox');

print "\n\nCtrl-C to keep from deleting \"$username\" - Return to DELETE THIS USER\n\n";
<STDIN>;

# Username should be lowercase:
$username =~ tr/A-Z/a-z/;

my $users = $macro->get_config($table);

my $dbh = $macro->_dbh();
my $sql = "delete from $users where username=?";
my $sth = $dbh->prepare($sql);
my $ret = $sth->execute($username);

print "Done! (return $ret)\n\n",
      "     Don't forget to run the cron processing script before you can generate the info page:\n",
      "     /var/www/macrophile.com/scripts/cron/daily.sh\n\n";
